ARG DOCKER_ARCH
FROM ${DOCKER_ARCH:-amd64}/alpine
ARG TAG
ARG GOARCH
ENV GOARCH ${GOARCH}
EXPOSE 7777
WORKDIR /app
VOLUME /root/.local/share/storj/gateway
COPY gateway_linux_${GOARCH:-amd64} /app/gateway
COPY entrypoint.noninteractive /entrypoint
ENV STORJ_CONFIG_DIR=/root/.local/share/storj/gateway \
    STORJ_SERVER_ADDRESS=0.0.0.0:7777 \
    STORJ_ACCESS= \
    STORJ_SAT_ADDRESS= \
    STORJ_API_KEY= \
    STORJ_PASSPHRASE=
ENTRYPOINT ["/entrypoint"]
